<?php

namespace Database\Seeders;

use App\Models\Conducta;
use Illuminate\Database\Seeder;

class ConductaSeeder extends Seeder
{
    public function run()
    {
        $data = [
            0 => [
                'id' => 1,
                'competencia_id' => 1,
                'descripcion' => 'Mantiene sus competencias actualizadas en función de los cambios que exige la administración pública en la prestación de un óptimo servicio',
                'activo' => true,
            ],
            1 => [
                'id' => 2,
                'competencia_id' => 1,
                'descripcion' => 'Gestiona sus propias fuentes de información confiable y/o participa de espacios informativos y de capacitación',
                'activo' => true,
            ],
            2 => [
                'id' => 3,
                'competencia_id' => 1,
                'descripcion' => 'Comparte sus saberes y habilidades con sus compañeros de trabajo, y aprende de sus colegas habilidades diferenciales, que le permiten nivelar sus conocimientos en flujos informales de inter-aprendizaje',
                'activo' => true,
            ],
            3 => [
                'id' => 4,
                'competencia_id' => 2,
                'descripcion' => 'Asume la responsabilidad por sus resultados',
                'activo' => true,
            ],
            4 => [
                'id' => 5,
                'competencia_id' => 2,
                'descripcion' => 'Trabaja con base en objetivos claramente establecidos y realistas',
                'activo' => true,
            ],
            5 => [
                'id' => 6,
                'competencia_id' => 2,
                'descripcion' => 'Diseña y utiliza indicadores para medir y comprobar los resultados obtenidos',
                'activo' => true,
            ],
            6 => [
                'id' => 7,
                'competencia_id' => 3,
                'descripcion' => 'Adopta medidas para minimizar riesgos',
                'activo' => true,
            ],
            7 => [
                'id' => 8,
                'competencia_id' => 3,
                'descripcion' => 'Plantea estrategias para alcanzar o superar los resultados esperados',
                'activo' => true,
            ],
            8 => [
                'id' => 9,
                'competencia_id' => 3,
                'descripcion' => 'Se fija metas y obtiene los resultados institucionales esperados',
                'activo' => true,
            ],
            9 => [
                'id' => 10,
                'competencia_id' => 3,
                'descripcion' => 'Cumple con oportunidad las funciones de acuerdo con los estándares, objetivos y tiempos establecidos por la entidad',
                'activo' => true,
            ],
            10 => [
                'id' => 11,
                'competencia_id' => 3,
                'descripcion' => 'Gestiona recursos para mejorar la productividad y toma medidas necesarias para minimizar los riesgos',
                'activo' => true,
            ],
            11 => [
                'id' => 12,
                'competencia_id' => 3,
                'descripcion' => 'Aporta elementos para la consecución de resultados enmarcando sus productos y/o servicios dentro de las normas que rigen a la entidad',
                'activo' => true,
            ],
            12 => [
                'id' => 13,
                'competencia_id' => 3,
                'descripcion' => 'Evalúa de forma regular el grado de consecución de los objetivos',
                'activo' => true,
            ],
            13 => [
                'id' => 14,
                'competencia_id' => 3,
                'descripcion' => 'Valora y atiende las necesidades y peticiones de los usuarios y de los ciudadanos de forma oportuna',
                'activo' => true,
            ],
            14 => [
                'id' => 15,
                'competencia_id' => 3,
                'descripcion' => 'Reconoce la interdependencia entre su trabajo y el de otros',
                'activo' => true,
            ],
            15 => [
                'id' => 16,
                'competencia_id' => 3,
                'descripcion' => 'Establece mecanismos para conocer las necesidades e inquietudes de los usuarios y ciudadanos',
                'activo' => true,
            ],
            16 => [
                'id' => 17,
                'competencia_id' => 3,
                'descripcion' => 'Incorpora las necesidades de usuarios y ciudadanos en los proyectos institucionales, teniendo en cuenta la visión de servicio a corto, mediano y largo plazo',
                'activo' => true,
            ],
            17 => [
                'id' => 18,
                'competencia_id' => 3,
                'descripcion' => 'Aplica los conceptos de no estigmatización y no discriminación y genera espacios y lenguaje incluyente',
                'activo' => true,
            ],
            18 => [
                'id' => 19,
                'competencia_id' => 3,
                'descripcion' => 'Escucha activamente e informa con veracidad al usuario o ciudadano',
                'activo' => true,
            ],
            19 => [
                'id' => 20,
                'competencia_id' => 4,
                'descripcion' => 'Promueve el cumplimiento de las metas de la organización y respeta sus normas',
                'activo' => true,
            ],
            20 => [
                'id' => 21,
                'competencia_id' => 4,
                'descripcion' => 'Antepone las necesidades de la organización a sus propias necesidades',
                'activo' => true,
            ],
            21 => [
                'id' => 22,
                'competencia_id' => 4,
                'descripcion' => 'Demuestra sentido de pertenencia en todas sus actuaciones',
                'activo' => true,
            ],
            22 => [
                'id' => 23,
                'competencia_id' => 4,
                'descripcion' => 'Toma iniciativa de colaborar con sus compañeros y con otras áreas cuando se requiere, sin descuidar sus tareas',
                'activo' => true,
            ],
            23 => [
                'id' => 24,
                'competencia_id' => 5,
                'descripcion' => 'Cumple los compromisos que adquiere con el equipo',
                'activo' => true,
            ],
            24 => [
                'id' => 25,
                'competencia_id' => 5,
                'descripcion' => 'Respeta la diversidad de criterios y opiniones de los miembros del equipo',
                'activo' => true,
            ],
            25 => [
                'id' => 26,
                'competencia_id' => 5,
                'descripcion' => 'Asume su responsabilidad como miembro de un equipo de trabajo y se enfoca en contribuir con el compromiso y la motivación de sus miembros',
                'activo' => true,
            ],
            26 => [
                'id' => 27,
                'competencia_id' => 5,
                'descripcion' => 'Planifica las propias acciones teniendo en cuenta su repercusión en la consecución de los objetivos grupales',
                'activo' => true,
            ],
            27 => [
                'id' => 28,
                'competencia_id' => 5,
                'descripcion' => 'Establece una comunicación directa con los miembros del equipo que permite compartir información e ideas en condición de respeto y cordialidad',
                'activo' => true,
            ],
            28 => [
                'id' => 29,
                'competencia_id' => 6,
                'descripcion' => 'Integra a los nuevos miembros y facilita su proceso de reconocimiento y apropiación de las actividades a cargo del equipo',
                'activo' => true,
            ],
            29 => [
                'id' => 30,
                'competencia_id' => 6,
                'descripcion' => 'Acepta y se adapta fácilmente a las nuevas situaciones',
                'activo' => true,
            ],
            30 => [
                'id' => 31,
                'competencia_id' => 6,
                'descripcion' => 'Responde al cambio con flexibilidad',
                'activo' => true,
            ],
            31 => [
                'id' => 32,
                'competencia_id' => 6,
                'descripcion' => 'Apoya a la entidad en nuevas decisiones y coopera activamente en la implementación de nuevos objetivos, forma de trabajo y procedimientos',
                'activo' => true,
            ],
            32 => [
                'id' => 33,
                'competencia_id' => 6,
                'descripcion' => 'Promueve al grupo para que se adapten en las nuevas condiciones',
                'activo' => true,
            ],
            33 => [
                'id' => 34,
                'competencia_id' => 7,
                'descripcion' => 'Mantiene actualizados sus conocimientos para apoyar la gestión de la entidad',
                'activo' => true,
            ],
            34 => [
                'id' => 35,
                'competencia_id' => 7,
                'descripcion' => 'Conoce, maneja y sabe aplicar los conocimientos para el logro de resultados',
                'activo' => true,
            ],
            35 => [
                'id' => 36,
                'competencia_id' => 7,
                'descripcion' => 'Emite conceptos técnicos u orientaciones claros, precisos, pertinentes y ajustados a los lineamientos normativos y organizacionales',
                'activo' => true,
            ],
            36 => [
                'id' => 37,
                'competencia_id' => 7,
                'descripcion' => 'Genera conocimientos técnicos de interés para la entidad, los cuales son aprehendidos y utilizados en el actuar de la organización',
                'activo' => true,
            ],
            37 => [
                'id' => 38,
                'competencia_id' => 8,
                'descripcion' => 'Apoya la generación de nuevas ideas y conceptos para el mejoramiento de la entidad',
                'activo' => true,
            ],
            38 => [
                'id' => 39,
                'competencia_id' => 8,
                'descripcion' => 'Prevé situaciones y alternativas de solución que orienten la toma de decisiones de la alta dirección',
                'activo' => true,
            ],
            39 => [
                'id' => 40,
                'competencia_id' => 8,
                'descripcion' => 'Reconoce y hace viables las oportunidades y las comparte con sus jefes para contribuir al logro de objetivos y metas institucionales',
                'activo' => true,
            ],
            40 => [
                'id' => 41,
                'competencia_id' => 8,
                'descripcion' => 'Adelanta estudios o investigaciones y los documenta, para contribuir a la dinámica de la entidad y su competitividad',
                'activo' => true,
            ],
            41 => [
                'id' => 42,
                'competencia_id' => 9,
                'descripcion' => 'Prevé situaciones y alternativas de solución que orientan la toma de decisiones de la alta dirección',
                'activo' => true,
            ],
            42 => [
                'id' => 43,
                'competencia_id' => 9,
                'descripcion' => 'Enfrenta los problemas y propone acciones concretas para solucionarlos',
                'activo' => true,
            ],
            43 => [
                'id' => 44,
                'competencia_id' => 9,
                'descripcion' => 'Reconoce y hace viables las oportunidades',
                'activo' => true,
            ],
            44 => [
                'id' => 45,
                'competencia_id' => 10,
                'descripcion' => 'Establece y mantiene relaciones cordiales y reciprocas con redes o grupos de personas internas y externas de la organización que faciliten la consecución de los objetivos institucionales',
                'activo' => true,
            ],
            45 => [
                'id' => 46,
                'competencia_id' => 10,
                'descripcion' => 'Utiliza contactos para conseguir objetivos',
                'activo' => true,
            ],
            46 => [
                'id' => 47,
                'competencia_id' => 10,
                'descripcion' => 'Comparte información para establecer lazos',
                'activo' => true,
            ],
            47 => [
                'id' => 48,
                'competencia_id' => 10,
                'descripcion' => 'Interactúa con otros de un modo efectivo y adecuado',
                'activo' => true,
            ],
            48 => [
                'id' => 49,
                'competencia_id' => 11,
                'descripcion' => 'Se informa permanentemente sobre políticas gubernamentales, problemas y demandas del entorno',
                'activo' => true,
            ],
            49 => [
                'id' => 50,
                'competencia_id' => 11,
                'descripcion' => 'Comprende el entorno organizacional que enmarca las situaciones objeto de asesoría y lo toma como referente',
                'activo' => true,
            ],
            50 => [
                'id' => 51,
                'competencia_id' => 11,
                'descripcion' => 'Identifica las fuerzas políticas que afectan la organización y las posibles alianzas y las tiene en cuenta al emitir sus conceptos técnicos',
                'activo' => true,
            ],
            51 => [
                'id' => 52,
                'competencia_id' => 11,
                'descripcion' => 'Orienta el desarrollo de estrategias que concilien las fuerzas políticas y las alianzas en pro de la organización',
                'activo' => true,
            ],
            52 => [
                'id' => 53,
                'competencia_id' => 12,
                'descripcion' => 'Aporta soluciones alternativas en lo que refiere a sus saberes específicos',
                'activo' => true,
            ],
            53 => [
                'id' => 54,
                'competencia_id' => 12,
                'descripcion' => 'Informa su experiencia especifica en el proceso de toma de decisiones que involucran aspectos de su especialidad',
                'activo' => true,
            ],
            54 => [
                'id' => 55,
                'competencia_id' => 12,
                'descripcion' => 'Anticipa problemas previsibles que advierte en su carácter de especialista',
                'activo' => true,
            ],
            55 => [
                'id' => 56,
                'competencia_id' => 12,
                'descripcion' => 'Asume la interdisciplinariedad aprendiendo puntos de vista diversos y alternativos al propio, para analizar y ponderar soluciones posibles',
                'activo' => true,
            ],
            56 => [
                'id' => 57,
                'competencia_id' => 13,
                'descripcion' => 'Utiliza canales de comunicación, en su diversa expresión, con claridad, precisión y tono agradable para el receptor',
                'activo' => true,
            ],
            57 => [
                'id' => 58,
                'competencia_id' => 13,
                'descripcion' => 'Redacta textos, informes, mensajes, cuadros o gráficas con claridad en la expresión para hacer efectiva y sencilla la comprensión',
                'activo' => true,
            ],
            58 => [
                'id' => 59,
                'competencia_id' => 13,
                'descripcion' => 'Mantiene escucha y lectura atenta a efectos de comprender mejor los mensajes o información recibida',
                'activo' => true,
            ],
            59 => [
                'id' => 60,
                'competencia_id' => 13,
                'descripcion' => 'Da respuesta a cada comunicación recibida de modo inmediato',
                'activo' => true,
            ],
            60 => [
                'id' => 61,
                'competencia_id' => 14,
                'descripcion' => 'Ejecuta sus tareas con los criterios de calidad establecidos',
                'activo' => true,
            ],
            61 => [
                'id' => 62,
                'competencia_id' => 14,
                'descripcion' => 'Revisa procedimientos e instrumentos para mejorar tiempos y resultados y para anticipar soluciones a problemas',
                'activo' => true,
            ],
            62 => [
                'id' => 63,
                'competencia_id' => 14,
                'descripcion' => 'Desarrolla las actividades de acuerdo con las pautas y protocolos definidos',
                'activo' => true,
            ],
            63 => [
                'id' => 64,
                'competencia_id' => 15,
                'descripcion' => 'Discrimina con efectividad entre las decisiones que deben ser elevadas a un superior, socializadas al equipo de trabajo o pertenecen a la esfera individual de trabajo',
                'activo' => true,
            ],
            64 => [
                'id' => 65,
                'competencia_id' => 15,
                'descripcion' => 'Adopta decisiones sobre ellas con base en información válida y rigurosa',
                'activo' => true,
            ],
            65 => [
                'id' => 66,
                'competencia_id' => 15,
                'descripcion' => 'Maneja criterios objetivos para analizar la materia a decidir con las personas involucradas',
                'activo' => true,
            ],
            66 => [
                'id' => 67,
                'competencia_id' => 15,
                'descripcion' => 'Asume los efectos de sus decisiones y también de las adoptadas por el equipo de trabajo al que pertenece',
                'activo' => true,
            ],
            67 => [
                'id' => 68,
                'competencia_id' => 16,
                'descripcion' => 'Aplica el conocimiento técnico en el desarrollo de sus responsabilidades',
                'activo' => true,
            ],
            68 => [
                'id' => 69,
                'competencia_id' => 16,
                'descripcion' => 'Mantiene actualizado su conocimiento técnico para apoyar su gestión',
                'activo' => true,
            ],
            69 => [
                'id' => 70,
                'competencia_id' => 16,
                'descripcion' => 'Resuelve problemas utilizando conocimientos técnicos de su especialidad, para apoyar el cumplimiento de metas y objetivos institucionales',
                'activo' => true,
            ],
            70 => [
                'id' => 71,
                'competencia_id' => 16,
                'descripcion' => 'Emite conceptos técnicos, juicios o propuestas claros, precisos, pertinentes y ajustados a los lineamientos normativos y organizacionales',
                'activo' => true,
            ],
            71 => [
                'id' => 72,
                'competencia_id' => 17,
                'descripcion' => 'Recibe instrucciones y desarrolla actividades acorde con las mismas',
                'activo' => true,
            ],
            72 => [
                'id' => 73,
                'competencia_id' => 17,
                'descripcion' => 'Acepta la supervisión constante',
                'activo' => true,
            ],
            73 => [
                'id' => 74,
                'competencia_id' => 17,
                'descripcion' => 'Revisa de manera permanente los cambios en los procesos',
                'activo' => true,
            ],
            74 => [
                'id' => 75,
                'competencia_id' => 18,
                'descripcion' => 'Maneja con responsabilidad las informaciones personales e institucionales de que dispone',
                'activo' => true,
            ],
            75 => [
                'id' => 76,
                'competencia_id' => 18,
                'descripcion' => 'Evade temas que indagan sobre información confidencial',
                'activo' => true,
            ],
            76 => [
                'id' => 77,
                'competencia_id' => 18,
                'descripcion' => 'Recoge solo información imprescindible para el desarrollo de la tarea',
                'activo' => true,
            ],
            77 => [
                'id' => 78,
                'competencia_id' => 18,
                'descripcion' => 'Organiza y custodia de forma adecuada la información a su cuidado, teniendo en cuenta las normas legales y de la organización',
                'activo' => true,
            ],
            78 => [
                'id' => 79,
                'competencia_id' => 18,
                'descripcion' => 'No hace pública la información laboral o de las personas que pueda afectar la organización o las personas',
                'activo' => true,
            ],
            79 => [
                'id' => 80,
                'competencia_id' => 18,
                'descripcion' => 'Transmite información oportuna y objetiva',
                'activo' => true,
            ],
            80 => [
                'id' => 81,
                'competencia_id' => 19,
                'descripcion' => 'Escucha con interés y capta las necesidades de los demás',
                'activo' => true,
            ],
            81 => [
                'id' => 82,
                'competencia_id' => 19,
                'descripcion' => 'Transmite la información de forma fidedigna evitando situaciones que puedan generar deterioro en el ambiente laboral',
                'activo' => true,
            ],
            82 => [
                'id' => 83,
                'competencia_id' => 19,
                'descripcion' => 'Toma la iniciativa en el contacto con usuarios para dar avisos, citas o respuestas, utilizando un lenguaje claro para los destinarios, especialmente con las personas que integran minorías con mayor vulnerabilidad social o con diferencias funcionales',
                'activo' => true,
            ],
            83 => [
                'id' => 84,
                'competencia_id' => 19,
                'descripcion' => 'Articula sus actuaciones con las de los demás',
                'activo' => true,
            ],
            84 => [
                'id' => 85,
                'competencia_id' => 19,
                'descripcion' => 'Cumple con los compromisos adquiridos',
                'activo' => true,
            ],
            85 => [
                'id' => 86,
                'competencia_id' => 19,
                'descripcion' => 'Facilita la labor de sus superiores y compañeros de trabajo',
                'activo' => true,
            ],
        ];
        foreach ($data as $item) {
            Conducta::firstOrCreate(['id' => $item['id']], $item);
        }
    }
}
